In [1]:
import pandas as pd

In [2]:
import numpy

# 5.1 Introduction to pandas Data Structures

### Series

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

And so on...

**Trying a bold markdown**

*Italic*

# Heading 1

## HEADING 2

# Quick Reminder on Markdown
### Use different amounts of pound signs for different heading emphasis
## Basic text formatting:
To make text **bold**, or *italic*, or ***bold and italic*** use stars.
> To make a block quote, use a carrot in the front

1. Lists can be made
1. With the same or different number each time
1. It will automatically renumber

- A single dash
- can be used
- for a bullet point list

Remember to set the cell type from Code to Markdown
and press the **Run** button to apply the formating.

The keyboard shortcut for markdown is m/M after intiating a new cell. 

### SERIES

The default index starts at 0

In [5]:
obj. values

array([ 4,  7, -5,  3])

.index describes the 3 'S' of range

In [6]:
obj.index 

RangeIndex(start=0, stop=4, step=1)

To assign value keys to the index:

In [7]:
obj2 = pd.Series([4, 7, -5, 3], index= ['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

Can use single or sets of values:

In [10]:
obj2['a']

-5

In [11]:
obj2['d'] = 6

In [12]:
obj2[['c', 'a', 'd',]]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [15]:
import numpy as np

In [16]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
'b' in obj2

True

In [18]:
'e' in obj2

False

In the following dict I entered the data as in the book, but theirs organized alphabetically, and mine stayed i entry order.

In [19]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [20]:
obj3 = pd.Series(sdata)

In [21]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [22]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [23]:
obj4 = pd.Series(sdata, index=states)

In [24]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [31]:
obj4.name = 'population'

In [32]:
obj4.index.name = 'state'

In [33]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [34]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [35]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [36]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DATAFRAME

In [37]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada','Nevada','Nevada'], 
        'year': [2000, 2001, 2002, 2001, 2002, 2003], 
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)


In [38]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [39]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [40]:
pd. DataFrame(data, columns = ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [41]:
frame2 = pd.DataFrame(data, columns= ['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four','five', 'six'])

In [42]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [43]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

m/M Retrieve a column with dict notation, or by attribute

In [44]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [45]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [46]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [47]:
frame2['debt'] = 16.5

In [48]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [49]:
frame2['debt'] = np.arange(6.)

In [50]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [51]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [52]:
frame2['debt'] = val 

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

^That one didn't work at first, because the mode of the cell got changed to "raw as opposed to "Code".

In [54]:
frame2['eastern'] = frame2.state == 'Ohio'

In [55]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [56]:
frame2['eastern'] = frame2.state == 'Ohio'

In [57]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [58]:
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'eastern'], dtype='object')

In [59]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [64]:
frame3 = pd.DataFrame(pop)

In [65]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [66]:
frame3.index.name = 'year'

In [67]:
frame3

Nevada  Ohio
year              
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [71]:
frame3.T

year    2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [73]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [75]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [76]:
pd.DataFrame(pdata)

Ohio  Nevada
year              
2001   1.7     2.4
2002   3.6     2.9

In [78]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [79]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [80]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [81]:
frame2.values

array([[2000, 'Ohio', 1.5, nan, True],
       [2001, 'Ohio', 1.7, -1.2, True],
       [2002, 'Ohio', 3.6, nan, True],
       [2001, 'Nevada', 2.4, -1.5, False],
       [2002, 'Nevada', 2.9, -1.7, False],
       [2003, 'Nevada', 3.2, nan, False]], dtype=object)

In [82]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [83]:
index = obj.index

In [84]:
index

Index(['a', 'b', 'c'], dtype='object')

In [85]:
index[1:]

Index(['b', 'c'], dtype='object')

In [86]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [88]:
labels = pd.Index(np.arange(3))

In [89]:
labels

Index([0, 1, 2], dtype='int64')

In [90]:
obj2 = pd.Series([1.5, -2.5, 0], index= labels)

In [91]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [92]:
obj2.index is labels

True

In [93]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [94]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [95]:
'Ohio' in frame3.columns

True

In [98]:
2003 in frame3.index

False

In [100]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [101]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [102]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])

In [103]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [104]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [105]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [107]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0,2,4])

In [108]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [109]:
obj3.reindex(range(6), method= 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [110]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [111]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [112]:
frame2= frame.reindex(['a', 'b', 'c', 'd'])

In [113]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [114]:
states= ['Texas', 'Utah', 'California']

In [115]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [121]:
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: "['b'] not in index"

In [122]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [123]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [124]:
new_obj = obj.drop('c')

In [125]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [126]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [127]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [128]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [129]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [130]:
data.drop(['two', 'four'], axis= 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [ ]:
obj.drop