In [1]:
import pandas as pd

In [2]:
import numpy

# 5.1 Introduction to pandas Data Structures

### Series

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

And so on...

**Trying a bold markdown**

*Italic*

# Heading 1

## HEADING 2

# Quick Reminder on Markdown
### Use different amounts of pound signs for different heading emphasis
## Basic text formatting:
To make text **bold**, or *italic*, or ***bold and italic*** use stars.
> To make a block quote, use a carrot in the front

1. Lists can be made
1. With the same or different number each time
1. It will automatically renumber

- A single dash
- can be used
- for a bullet point list

Remember to set the cell type from Code to Markdown
and press the **Run** button to apply the formating.

The keyboard shortcut for markdown is m/M after intiating a new cell. 

### SERIES

The default index starts at 0

In [5]:
obj. values

array([ 4,  7, -5,  3])

.index describes the 3 'S' of range

In [6]:
obj.index 

RangeIndex(start=0, stop=4, step=1)

To assign value keys to the index:

In [7]:
obj2 = pd.Series([4, 7, -5, 3], index= ['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

Can use single or sets of values:

In [10]:
obj2['a']

-5

In [11]:
obj2['d'] = 6

In [12]:
obj2[['c', 'a', 'd',]]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [15]:
import numpy as np

In [16]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
'b' in obj2

True

In [18]:
'e' in obj2

False

In the following dict I entered the data as in the book, but theirs organized alphabetically, and mine stayed i entry order.

In [19]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [20]:
obj3 = pd.Series(sdata)

In [21]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [22]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [23]:
obj4 = pd.Series(sdata, index=states)

In [24]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [31]:
obj4.name = 'population'

In [32]:
obj4.index.name = 'state'

In [33]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [34]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [35]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [36]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DATAFRAME

In [37]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada','Nevada','Nevada'], 
        'year': [2000, 2001, 2002, 2001, 2002, 2003], 
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)


In [38]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [39]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [40]:
pd. DataFrame(data, columns = ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [41]:
frame2 = pd.DataFrame(data, columns= ['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four','five', 'six'])

In [42]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [43]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

m/M Retrieve a column with dict notation, or by attribute

In [44]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [45]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [46]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [47]:
frame2['debt'] = 16.5

In [48]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [49]:
frame2['debt'] = np.arange(6.)

In [50]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [51]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [52]:
frame2['debt'] = val 

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

^That one didn't work at first, because the mode of the cell got changed to "raw as opposed to "Code".

In [54]:
frame2['eastern'] = frame2.state == 'Ohio'

In [55]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [56]:
frame2['eastern'] = frame2.state == 'Ohio'

In [57]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [58]:
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'eastern'], dtype='object')

In [59]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [64]:
frame3 = pd.DataFrame(pop)

In [65]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [66]:
frame3.index.name = 'year'

In [67]:
frame3

Nevada  Ohio
year              
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [71]:
frame3.T

year    2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [73]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [75]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [76]:
pd.DataFrame(pdata)

Ohio  Nevada
year              
2001   1.7     2.4
2002   3.6     2.9

In [78]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [79]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [80]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [81]:
frame2.values

array([[2000, 'Ohio', 1.5, nan, True],
       [2001, 'Ohio', 1.7, -1.2, True],
       [2002, 'Ohio', 3.6, nan, True],
       [2001, 'Nevada', 2.4, -1.5, False],
       [2002, 'Nevada', 2.9, -1.7, False],
       [2003, 'Nevada', 3.2, nan, False]], dtype=object)

In [82]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [83]:
index = obj.index

In [84]:
index

Index(['a', 'b', 'c'], dtype='object')

In [85]:
index[1:]

Index(['b', 'c'], dtype='object')

In [86]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [88]:
labels = pd.Index(np.arange(3))

In [89]:
labels

Index([0, 1, 2], dtype='int64')

In [90]:
obj2 = pd.Series([1.5, -2.5, 0], index= labels)

In [91]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [92]:
obj2.index is labels

True

In [93]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [94]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [95]:
'Ohio' in frame3.columns

True

In [98]:
2003 in frame3.index

False

In [100]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [101]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [102]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])

In [103]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [104]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [105]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [107]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0,2,4])

In [108]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [109]:
obj3.reindex(range(6), method= 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [110]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [111]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [112]:
frame2= frame.reindex(['a', 'b', 'c', 'd'])

In [113]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [114]:
states= ['Texas', 'Utah', 'California']

In [115]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [121]:
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: "['b'] not in index"

In [122]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [123]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [124]:
new_obj = obj.drop('c')

In [125]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [126]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [127]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [128]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [129]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [153]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [154]:
data.drop(['two', 'four'], axis= 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [155]:
obj.drop('c', inplace=True)

## Inplace drops the data in the column

In [156]:
obj

a    0.0
b    5.0
d    3.0
dtype: float64

In [157]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [158]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [159]:
obj['b']

1.0

In [160]:
obj[1]

/var/folders/fy/thq20n_j7rg3ycyq1v1s6gzh0000gp/T/ipykernel_34705/2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]


1.0

In [161]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [162]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [163]:
obj[[1,3]]

/var/folders/fy/thq20n_j7rg3ycyq1v1s6gzh0000gp/T/ipykernel_34705/1781339481.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1,3]]


b    1.0
d    3.0
dtype: float64

In [164]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [165]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [166]:
obj['b':'c'] = 5

In [144]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [167]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
index=['Ohio', 'Colorado', 'Utah', 'New York'],
columns=['one', 'two', 'three', 'four'])

In [168]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [169]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [170]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [171]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [172]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

## This is interesting because it's a boolean, not returning the values that are lesss than 5, just whether or not the value is less than 5!

In [176]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [177]:
data[data < 5] = 0

In [178]:
data 

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [179]:
data.loc['Colorado', ['two', 'three']] 


two      5
three    6
Name: Colorado, dtype: int64

## In the iloc query the first index is the column, and the second nested index is the row

In [181]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [182]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

## For searching row and column axis, both have to be encapsulated in an outside bracket

In [185]:
data.iloc[[1,2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

## What data lies between [0] and [Utah] in the state column as well as the two column

In [187]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

## Collection of data encompassed by three from the end, and as far as column three

In [189]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

## The wrong way to do things

In [195]:
ser = pd.Series(np.arange(3.))
ser
ser[-1]

KeyError: -1

## Integer Indexes have potential for ambiguity

In [196]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [198]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [199]:
ser2[-1]

/var/folders/fy/thq20n_j7rg3ycyq1v1s6gzh0000gp/T/ipykernel_34705/811950851.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[-1]


2.0

In [200]:
ser[:1]

0    0.0
dtype: float64

In [201]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [202]:
ser.iloc[:1]

0    0.0
dtype: float64

In [203]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [205]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [206]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [207]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [208]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [209]:
df1= pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])

In [210]:
df2= pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [211]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [212]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [213]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [214]:
df1 = pd.DataFrame({'A': [1,2]})

In [215]:
df2 = pd.DataFrame({'B': [3,4]})

In [216]:
df1

A
0  1
1  2

In [217]:
df2

B
0  3
1  4

In [218]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [219]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                   columns=list('abcd'))

In [221]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                   columns=list('abcde'))

In [222]:
df2.loc[1,'b'] = np.nan

In [223]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [224]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [225]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [226]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [227]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [228]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [229]:
arr = np.arange(12.).reshape((3,4))

In [230]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [231]:
arr[0]

array([0., 1., 2., 3.])

In [232]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [234]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [235]:
series = frame.iloc[0]

In [236]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

## Because this variable refers to a specific row, calling the variable returns the row

In [237]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [238]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [239]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [240]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [241]:
series3 = frame['d']

In [242]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [243]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [244]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [245]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), 
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [246]:
frame

b         d         e
Utah    0.756168 -1.341389 -0.732149
Ohio    0.917498  0.670970 -0.142559
Texas   0.365312 -0.260772  0.866982
Oregon -1.249238  1.991603  0.530042

In [247]:
np.abs(frame)

b         d         e
Utah    0.756168  1.341389  0.732149
Ohio    0.917498  0.670970  0.142559
Texas   0.365312  0.260772  0.866982
Oregon  1.249238  1.991603  0.530042

In [248]:
f = lambda x: x.max() - x.min()

In [249]:
frame.apply(f)

b    2.166736
d    3.332992
e    1.599132
dtype: float64

In [250]:
frame.apply(f, axis= 'columns')

Utah      2.097557
Ohio      1.060057
Texas     1.127755
Oregon    3.240841
dtype: float64

In [255]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [256]:
frame.apply(f)

b         d         e
min -1.249238 -1.341389 -0.732149
max  0.917498  1.991603  0.866982

In [258]:
format = lambda x: '%.2f'% x

In [260]:
frame.map(format)

b      d      e
Utah     0.76  -1.34  -0.73
Ohio     0.92   0.67  -0.14
Texas    0.37  -0.26   0.87
Oregon  -1.25   1.99   0.53

In [261]:
frame['e'].map(format)

Utah      -0.73
Ohio      -0.14
Texas      0.87
Oregon     0.53
Name: e, dtype: object

In [275]:
obj = pd.Series(range(4), 
                index=['d', 'a', 'b', 'c'])

In [276]:
obj.sort=index()

TypeError: 'tuple' object is not callable